<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-11P1576" failures="2" tests="6" name="Test" time="0.297" errors="0" timestamp="2023-08-13T14:34:00 IST">
  <testcase classname="FailedTestCaseRetry.FailedTestCase" name="TestCase01" time="0.047">
    <skipped/>
  </testcase> <!-- TestCase01 -->
  <testcase classname="FailedTestCaseRetry.FailedTestCase" name="TestCase01" time="0.002">
    <skipped/>
  </testcase> <!-- TestCase01 -->
  <testcase classname="FailedTestCaseRetry.FailedTestCase" name="TestCase01" time="0.03">
    <skipped/>
  </testcase> <!-- TestCase01 -->
  <testcase classname="FailedTestCaseRetry.FailedTestCase" name="TestCase01" time="0.008">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at FailedTestCaseRetry.FailedTestCase.TestCase01(FailedTestCase.java:13)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestCase01 -->
  <testcase classname="FailedTestCaseRetry.FailedTestCase" name="TestCase02" time="0.004">
    <failure type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError
at junit.framework.Assert.fail(Assert.java:47)
at junit.framework.Assert.assertTrue(Assert.java:20)
at junit.framework.Assert.assertTrue(Assert.java:27)
at FailedTestCaseRetry.FailedTestCase.TestCase02(FailedTestCase.java:21)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- TestCase02 -->
  <testcase classname="FailedTestCaseRetry.FailedTestCase" name="TestCase03" time="0.002"/>
</testsuite> <!-- Test -->
